services:

  postgres:
    image: postgres:16-alpine
    container_name: aegis-postgres
    environment:
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis
      POSTGRES_DB: aegis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aegis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegis -d aegis"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: aegis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aegis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:4.0.0
    container_name: aegis-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - aegis-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  aegis:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: aegis-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://aegis:aegis@postgres:5432/aegis
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8000:8000"
    networks:
      - aegis-network

  kafka-consumer:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: aegis-kafka-consumer
    command: python -m app.kafka_consumer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: aegis-incidents
      KAFKA_GROUP_ID: aegis-python-consumer
    networks:
      - aegis-network

  telemetry-consumer:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: aegis-telemetry-consumer
    command: python -m app.telemetry_consumer
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://aegis:aegis@postgres:5432/aegis
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TELEMETRY_TOPIC: telemetry
    networks:
      - aegis-network

  java-service:
    build:
      context: ./java-service
    container_name: aegis-java-service
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aegis
      SPRING_DATASOURCE_USERNAME: aegis
      SPRING_DATASOURCE_PASSWORD: aegis
    ports:
      - "8081:8081"
    networks:
      - aegis-network

  cpp-service:
    build:
      context: ./cpp-service
    container_name: aegis-cpp-service
    ports:
      - "8082:8082"
    networks:
      - aegis-network

  minio:
    image: minio/minio:latest
    container_name: aegis-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: aegis
      MINIO_ROOT_PASSWORD: aegis12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - aegis-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio-init:
    image: minio/mc:latest
    container_name: aegis-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 aegis aegis12345 &&
      mc mb -p local/aegis-lake &&
      exit 0
      "
    networks:
      - aegis-network

  spark-job:
    build:
      context: ./spark-job
    container_name: aegis-spark-job
    depends_on:
      kafka:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: aegis-incidents
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: aegis
      S3_SECRET_KEY: aegis12345
      S3_BUCKET: aegis-lake
    networks:
      - aegis-network

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  minio_data:

networks:
  aegis-network:
    driver: bridge