"""Evidence package for the LLM (pure).

The LLM only ever sees this package, and its answer may only cite references that exist in it.
Everything measured comes from the blast-radius analysis / signatures; documents come from
the knowledge base. Nothing here is generated by a model.
"""
import re

from app.analysis.resilience import END_USERS

MAX_DOC_CHARS = 700
MAX_HISTORY = 5


def _round(value):
    return round(value, 1) if isinstance(value, float) else value


def _service_facts(entry: dict) -> dict:
    return {
        "role": entry.get("role"),
        "status": entry["status"],
        "impact_pct": entry["impact_pct"],
        "baseline_p95_ms": entry["baseline"].get("p95_ms"),
        "fault_p95_ms": entry["fault"].get("p95_ms"),
        "p95_ratio": entry.get("p95_ratio"),
        "fault_error_pct": entry["fault"].get("error_pct"),
        "fault_status_counts": entry["fault"].get("status_counts"),
        "requests_in_fault_window": entry["fault"]["requests"],
    }


def build_experiment_evidence(experiment: dict, result: dict, history: list[dict], resilience: dict,
                              documents: list[dict]) -> dict:
    """experiment: engine dict; result: analysis output; history: related signature rows
    [{"id","signature"}]; resilience: {service: profile}; documents: [{"ref","title","source","text"}]."""
    services = {name: _service_facts(e) for name, e in result.get("services", {}).items()}
    end_user = next((v for v in services.values() if v["role"] == "client"), None)
    target = services.get(experiment["target"])
    hist = []
    for row in history[:MAX_HISTORY]:
        sig = row["signature"]
        eu = (sig["observed"].get("end_user") or {}).get("impact_pct")
        hist.append({"signature_id": row["id"], "target": sig["trigger"]["target"],
                     "fault_type": sig["trigger"]["fault_type"], "parameters": sig["trigger"]["parameters"],
                     "kind": sig["kind"], "end_user_impact_pct": eu,
                     "affected_services": sig["observed"]["affected_services"],
                     "recovery_s": sig["observed"]["recovery"].get("recovery_s")})
    win = result.get("windows", {})
    return {
        "summary": deterministic_summary(experiment, result),
        "experiment": {
            "id": experiment["id"], "target": experiment["target"], "fault_type": experiment["fault_type"],
            "parameters": experiment["parameters"], "dry_run": experiment["dry_run"],
            "workload_rps": experiment.get("workload_rps"), "workload_n": experiment.get("workload_n"),
            "fault_window_s": win.get("fault", {}).get("seconds"),
        },
        "measured": {
            "services": services,
            "target": target,
            "end_user": end_user,
            "affected_services": result.get("affected_services", []),
            "direct": result.get("direct", []),
            "indirect": result.get("indirect", []),
            "propagation": result.get("propagation", {}).get("paths", []),
            "recovery": {k: v for k, v in result.get("recovery", {}).items() if k != "per_service"},
            "warnings": result.get("quality", {}).get("warnings", []),
        },
        "history": hist,
        "resilience": {n: {"worst_case_score": p["worst_case_score"], "level": p["level"],
                           "confidence": p["confidence"], "critical_dependency": p["critical_dependency"]}
                       for n, p in resilience.items() if p.get("worst_case_score") is not None and n != END_USERS},
        "documents": [{"ref": d["ref"], "title": d["title"], "source": d["source"],
                       "text": d["text"][:MAX_DOC_CHARS]} for d in documents],
    }


def valid_refs(evidence: dict) -> set[str]:
    """Every reference the model is allowed to cite."""
    refs: set[str] = set()
    m = evidence.get("measured", {})
    refs.update(f"measured.services.{name}" for name in m.get("services", {}))
    for key in ("target", "end_user", "recovery"):
        if m.get(key) is not None:
            refs.add(f"measured.{key}")
    refs.update(f"measured.propagation.{i}" for i in range(len(m.get("propagation", []))))
    refs.update(f"history.{i}" for i in range(len(evidence.get("history", []))))
    refs.update(f"resilience.{name}" for name in evidence.get("resilience", {}))
    refs.update(d["ref"] for d in evidence.get("documents", []))
    if m.get("warnings"):
        refs.add("measured.warnings")
    return refs


def numeric_facts(evidence: dict) -> list[float]:
    """All numbers in the evidence; used to catch invented statistics in model output."""
    found: list[float] = []

    def walk(node):
        if isinstance(node, bool):
            return
        if isinstance(node, (int, float)):
            found.append(float(node))
        elif isinstance(node, dict):
            for k, v in node.items():
                if isinstance(k, str):
                    found.extend(float(x) for x in re.findall(r"\d+(?:\.\d+)?", k))  # e.g. status-code keys "502"
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)
        elif isinstance(node, str):
            found.extend(float(x) for x in re.findall(r"\d+(?:\.\d+)?", node))

    walk({k: v for k, v in evidence.items()})
    return found


def deterministic_summary(experiment: dict, result: dict) -> str:
    """Plain-language summary produced by code, never by a model. Always available."""
    if result.get("status") != "analyzed":
        return f"Experiment {experiment['id'][:8]} could not be analysed: {result.get('reason', 'no analysis')}."
    t = experiment
    kind = "Control run (no fault applied)" if t["dry_run"] else \
        f"{t['fault_type']} on {t['target']} {t['parameters'] or ''}".strip()
    parts = [f"{kind}."]
    eu = next((e for e in result["services"].values() if e.get("role") == "client"), None)
    if eu and eu["impact_pct"] is not None:
        parts.append(f"End users: {eu['impact_pct']}% of requests degraded "
                     f"(p95 {eu['baseline'].get('p95_ms')} ms -> {eu['fault'].get('p95_ms')} ms, "
                     f"{eu['fault'].get('error_pct')}% errors).")
    if result["affected_services"]:
        direct, indirect = result["direct"], result["indirect"]
        parts.append(f"Affected services: {', '.join(result['affected_services'])}"
                     f"{' (direct: ' + ', '.join(direct) + ')' if direct else ''}"
                     f"{' (indirect: ' + ', '.join(indirect) + ')' if indirect else ''}.")
        if result["propagation"]["paths"]:
            parts.append("Propagation: " + "; ".join(result["propagation"]["paths"]) + ".")
    else:
        parts.append("No service was measurably affected.")
    rec = result["recovery"]
    if rec.get("recovery_s") is not None:
        parts.append(f"Recovery: {rec['recovery_s']} s after the fault was removed.")
    elif rec.get("status") not in (None, "nothing_to_recover"):
        parts.append(f"Recovery status: {rec['status']}.")
    return " ".join(parts)
